use userdb999;
# select * from cars;
# select * from cars where year<2000;
# select * from cars where year>2015;
# select * from cars where year in (2008,2009,2010);
# select * from cars where year not in(2008, 2009, 2010);
# select * from cars where year = price;
# select * from cars where model = 'bmw' and year <2014;
# select * from cars where model = 'audi' and year>2014; /*-таких в списку немає-*/
# select * from cars limit 5;
# select * from cars limit 5 offset 212;
# select avg(price) as avgPrice from cars where model ='kia';
# select avg(price) as avgPrice from cars where model ='audi';
# select avg(price) as avgPrice from cars where model ='bmw';
# select avg(price) as avgPrice from cars where model ='daewoo';
# select avg(price) as avgPrice from cars where model ='kengo';
# select avg(price) as avgPrice from cars where model ='lada';
# select avg(price) as avgPrice from cars where model ='merc';
# select avg(price) as avgPrice from cars where model ='peugeot';
# select avg(price) as avgPrice from cars where model ='reno';
# select avg(price) as avgPrice from cars where model ='tesla';
# select avg(price) as avgPrice from cars where model ='toyota';
# select avg(price) as avgPrice from cars where model ='zoka';
# select count(*) as count from cars where model = 'audi';
# select count(*) as count from cars where model = 'kia';
# select count(*) as count from cars where model = 'bmw';
# select count(*) as count from cars where model = 'daewoo';
# select count(*) as count from cars where model = 'kengo';
# select count(*) as count from cars where model = 'lada';
# select count(*) as count from cars where model = 'merc';
# select count(*) as count from cars where model = 'peugeot';
# select count(*) as count from cars where model = 'reno';
# select count(*) as count from cars where model = 'tesla';
# select count(*) as count from cars where model = 'toyota';
# select count(*) as count from cars where model = 'zoka';
# select count(*), model as count from cars group by model;
# select * from cars where model like '_a%a_';
# select * from cars where length(model)>=8;
# select * from cars where price>(select avg(price) as avgPrice from cars);
